name: Deploy to AWS Lambda via Serverless

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy with Serverless
    runs-on: ubuntu-latest
    environment: Production - budget

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Serverless CLI
        run: npm install -g serverless

      - name: Deploy to AWS using Serverless
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}  # ✅ Required by serverless.yml
        run: serverless deploy
